services:
  postgres:
    image: postgres:18-alpine
    container_name: citeseer-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: citeseer
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: citeseer
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U citeseer -d citeseer']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
