apiVersion: 1

datasources:
  - name: DuckDB
    uid: DuckDB
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /data/analytics.sqlite
